workflows:
  test-build:
    name: Evil Invaders II Test Build
    instance_type: mac_mini_m1
    environment:
      node: 16.17.0
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Setup Capacitor iOS
        script: |
          npx cap add ios
          npx cap sync ios
    artifacts:
      - dist/
